### ISSUE TITLE
Add property to indicate the rel value that was used in the link to the source

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/webmention.io#11]
Add to the bottom of the API payload, `target_rel:["invitee"]`

**Comment by csarven** [comment]
If I understand this issue/feature then there may actually be more than one relation/property value between source and target, or be open to that possibility and handle it as desired, e.g., take all of them, or pick one.

Having this feature would be great because then we can work with the proposed http://csarven.ca/webmention#property-parameter extension :smile:

**Comment by aaronpk** [comment]
This is added in the jf2 format of the API, with the name "wm-property"
