### ISSUE TITLE
Feature request: report spam

### ISSUE THREAD

**Issue by fluffy-critter** [aaronpk/webmention.io#115]
I've started getting spammy webmentions via webmention.io, and it would be great if I could report them as spam when I delete them. Not necessarily to have any action taken now, but so that in the future some basic spam-mitigation measures could be built based on whatever patterns emerge from spam reports.

This feels like something that should be at least measured sooner rather than later, so that better tools can be built for the future when spammers inevitably run amok. :)

**Comment by aaronpk** [comment]
If you log in, you'll see the most recent 20 or so webmentions you've received and you can delete them from there. It'd be a good idea for me to separate that into delete as well as report as spam though. 

Do you have the pingback endpoint on your site too? I suspect these are actually spam pingbacks, since we've only seen one occurrence of webmention spam so far. I'd be really interested to know if it's actually spam sent by webmention tho!

**Comment by fluffy-critter** [comment]
I do have the pingback endpoint set as well, and that would make sense.

And I'm aware of being able to delete them, which is what I've been doing so far. :)

Your response does raise another question for me though -- do the stored webmentions eventually stop being stored? I was under the impression that I'd be able to use webmention.io as a sort of persistent store/inbox for my webmentions while I figure out what I'm going to actually do with them in the long run.

**Comment by aaronpk** [comment]
It doesn't delete anything you've received unless you delete it yourself. It's just the dashboard page only shows the most recent 20 right now. I should really add paging so you can look through more of them on the site. The API will provide you with all of them.

**Comment by fluffy-critter** [comment]
The new blocklist functionality is great! Thank you so much.
