### ISSUE TITLE
Webhook page doesn't have any input visible

### ISSUE THREAD

**Issue by mbifulco** [aaronpk/webmention.io#154]
Hey there - I recently migrated my blog from https://mike.biful.co to https://mikebifulco.com (via 301 redirects). I'm not sure if this has anything to do with the bug I'm experiencing, but I thought it might be helpful background, since after moving domains, webmentions no longer seem to work for my site.

Previously, webmentions were working on my site - after the domain switch, I went to set up a new webhook at https://webmention.io/settings/webhooks - this is what I see:

![image](https://user-images.githubusercontent.com/1844496/82733380-6720d100-9ce1-11ea-9bd7-d1756de26ff8.png)

I believe there [should be _something_ on this page](https://github.com/aaronpk/webmention.io/blob/master/views/webhooks.erb#L14) to let me input a URL for a webhook - but I'm not seeing anything.  

Any help is appreciated - I'm not sure what else to do at this point!

**Comment by aaronpk** [comment]
This isn't ideal, but you'll need to receive at least one webmention before the place to set up the web hook appears. 

If you're logging in as your new domain, all the previous webmentions won't be on that account. If you'd like I can set it up to move those to the new domain within webmention.io so you can continue to access them.

**Comment by mbifulco** [comment]
That would be great - thanks @aaronpk!

**Comment by aaronpk** [comment]
Looking into this, there's another problem here which is that your website is confused about `www`. I see a rel=canonical link to `https://mikebifulco.com/`, but that actually redirects to `https://www.mikebifulco.com/`. It looks like your intent is to not have the `www` subdomain, so you should look into that first before continuing with webmention.io since that's going to cause other problems there too.

**Comment by mbifulco** [comment]
I was just going to say that! It looks like brid.gy is sending webmentions for mikebifulco.com and not www.mikebifulco.com - I'll sort through that mess and get back to you here if I've got any questions.  Thanks for being so responsive!

**Comment by mbifulco** [comment]
Okay @aaronpk I'm back with a question - I think I've got all of the URL stuff sorted.  Everything should be pointed to `mikebifulco.com` rather than `www.` now.  

It looks like Bridgy is trying to send notifications to the wrong URL, though - it keeps sending off things that look like this:
`https://mikebifulco.com/why-fathom-analytics,%20/why-fathom-analytics/` - with an extra `,%20/why-fathom-analytics` at the end.  Have you seen that before? I'm at a loss for what might cause that

**Comment by aaronpk** [comment]
There's still something funny with your redirects.

Your tweet links to `https://t.co/QieYBXHzjj` which redirects to `https://www.mikebifulco.com/why-fathom-analytics`

that is a redirect to `https://mikebifulco.com/why-fathom-analytics`

*that* then sends another redirect to `/why-fathom-analytics/` without the hostname. I'm not sure where the comma is coming from, but you should probably clean that up again, or try another tweet with the final URL of your post instead of one that goes through these hops.

It's probably also worth fixing your final redirect to include the hostname instead of just the path.

**Comment by aaronpk** [comment]
actually it's even weirder than that... your URL at `https://mikebifulco.com/why-fathom-analytics` returns the contents of the page but *also* send a `Location: /why-fathom-analytics/` header. The URL `https://mikebifulco.com/why-fathom-analytics/` also returns the contents of the page, but does not return another `Location` header.

**Comment by mbifulco** [comment]
`psyduck.gif` oh god, what did I do?? Ha, what a mess.  Thanks for the second set of eyes @aaronpk - are you just inspecting network traffic to see all that?

**Comment by aaronpk** [comment]
I was testing with curl, and telling it to follow 0 redirects so that I can see each step. Also curl while outputting the headers will show the complete list of HTTP requests.

**Comment by mbifulco** [comment]
Hey there @aaronpk - I'd love to take you up on moving the webmentions from my old domain to the new one, if you're still able!

**Comment by aaronpk** [comment]
okay! I see a few webmentions on the new account. can I just drop those? It'll be easier if I can move your old account (mike.biful.co) on top of your new one (mikebifulco.com).

**Comment by mbifulco** [comment]
That's fine by me. Thank you!

- Mike

**Comment by aaronpk** [comment]
Okay can you log out and log back in and see if things look right?

**Comment by mbifulco** [comment]
Looks good @aaronpk - I think they'll deploy the next time I see a mention. thank you!
