### ISSUE TITLE
"Only send notifications about new webmentions" is not working as intended

### ISSUE THREAD

**Issue by petermolnar** [aaronpk/webmention.io#159]
The comment on https://github.com/aaronpk/webmention.io/blob/main/helpers/webmention_processor.rb#L246 says notifications should only be sent about new webmentions. Greg, from https://unrelenting.technology, re-sends all 5 webmentions he has on his site to mine, every day, and I always get those as new notifications through the webhook. (The source/target/dates are at the bottom).

I believe the notification block needs to be moved, maybe even out of the WebmentionProcessor to it's separate schedule, so that the "only new" feature works again.

I've started making myself familiar with the code, but given I'm not (yet) running and instance, it seems hard to test.

The daily webmentions themselves:

```
at: 2017-02-26T17:05:11
source: https://unrelenting.technology/replies/2017-02-26-17-05-11
target: https://petermolnar.net/switcing-from-thinkpad-x200-to-x250/
```

```
at: 2016-03-11T17:20:32
source: https://unrelenting.technology/likes/2016-03-11-17-20-32
target: https://petermolnar.eu/lightweight-system-monitoring-with-collectd-and-jarmon/
```

```
at: 2017-01-08T11:19:31
source: https://unrelenting.technology/likes/2017-01-08-11-19-31
target: https://petermolnar.net//beddgelert
```

```
at: 2017-01-05T02:24:41
source: https://unrelenting.technology/replies/2017-01-05-02-24-41
target: https://petermolnar.net//going-static
```

```
at: 2017-06-05T10:46:16
source: https://unrelenting.technology/replies/2017-06-05-10-46-16
target: https://petermolnar.net/trackpoint-drifting-stop/
```

**Comment by aaronpk** [comment]
I'm ripping out the notifications thingy which is why I noticed this. The notifications code you dug up actually has nothing to do with the webhooks. It's for generating text like "greg posted a note that linked to ____", but it never worked quite right.

It's actually intentional that the webhook runs each time the webmention is re-sent, since that's how you would find out if the original post had been updated. It's up to the webhook receiver to decide whether the post content changed and how to deal with it.
