### ISSUE TITLE
Ignore Query Parameters?

### ISSUE THREAD

**Issue by caseywatts** [aaronpk/webmention.io#186]
It looks like Webmention.io is sensitive to URL query parameters

Some links Webmention.io picks up from Mastodon etc have something like `?amp` or `?utm_source` etc in theme. 

These show up in the webmention.io database/dashboard, but not in this api call. Here's an example one that's missing a bunch of mentions because of the query parameters.
https://webmention.io/api/mentions.jf2?target=https://www.caseywatts.com/blog/welcome-to-mastodon/

I wonder if there already is (or could be) a way to make this api call query-parameter agnostic?

**Comment by aaronpk** [comment]
This is a bit of a mess, because for some sites, query parameters do return actually different posts. For example, posts on wordpress can have a custom permalink like `https://example.com/yyyy/mm/dd/slug` but are also retrievable from a URL like `https://example.com/?post_id=x`. So some query parameters are significant and others are not. 

I would suggest filing an issue upstream to whatever is sending webmentions from Mastodon URLs to not include the query parameters there instead. (But also, webmentions from Mastodon died a while ago when Mastodon switched to being a JS frontend instead of returning HTML web pages.)
