### ISSUE TITLE
Add support for Trackback as well

### ISSUE THREAD

**Issue by singpolyma** [aaronpk/webmention.io#51]
A much simpler protocol than pingback (basically the same as webmention), would be nice to unify all of these.

**Comment by aaronpk** [comment]
I reviewed the [Trackback protocol](http://archive.cweiske.de/trackback/trackback-1.2.html), and there is no way I'm going to add support for it. Trackback appears to have no mechanism to verify a trackback request is valid, meaning any trackback request sent is treated as valid, even if the URL doesn't exist. (This is demonstrated in practice by the vast amount of Trackback spam in the wild.) This makes it fundamentally different from Webmention which requires a webmention endpoint go and verify the source URL actually links to the target (the same mechanism that Pingback uses).

As much as I dislike Pingback requiring XMLRPC requests and responses, I decided to implement that in webmention.io because Pingback requires validating the source URL and is still widely in use by many blogging platforms. At least now I can use webmention.io's Pingback forwarding mechanism which translates Pingback requests to the simpler Webmention protocol.

I wouldn't even know how to go about the "autodiscovery" part of Trackback, since it apparently requires looking for custom tags or looking at tags inside HTML comments. ("Note: because current validators choke on RDF embedded in XHTML, if you want your pages to validate you may wish to enclose the above RDF in HTML comments...")

**Comment by aaronpk** [comment]
There is more information about these issues available on the IndieWebCamp wiki: http://indiewebcamp.com/Trackback

**Comment by singpolyma** [comment]
> Trackback appears to have no mechanism to verify a trackback request is valid

Same one as webmention -- check that the source page links to you.  The spec doesn't mention it, but it's a totally reasonable thing to do.

The RDF autodiscovery is a bit more of a pain, for sure.

**Comment by tantek** [comment]
In addition "would be nice to unify all of these" is flawed methodology per XKCD 927.

**Comment by singpolyma** [comment]
@tantek XKCD927 is the existing problem.  What webmention.io/brid.gy and other do is the solution (unification via translation).  All these communities insist on making new protocols every few years.  I just want a web that works :P  We're getting there, slowly.  brid.gy may be the best thing to happen in that regard, ever.
