### ISSUE TITLE
Missing values for nested h-entry

### ISSUE THREAD

**Issue by rhiaro** [aaronpk/webmention.io#52]
This issue doesn't really belong here because I _think_ it's a bug/not-yet-implemented in the Ruby parser, but it's affecting my mentions received at webmention.io so I'm putting it here for now anyway.

When a wm is received from a h-entry that is nested as a child of another, it is verified okay but the url, content, name, author, etc aren't picked up, see: http://webmention.io/api/mentions?target=http://rhiaro.co.uk/2015/08/threaded-replies

ie. This happens if a reply is in a thread, and doesn't have a permalink where it's the top level h-entry.

The PHP parser picks up the microformats just fine: http://pin13.net/mf2/?url=http://csarven.ca/webmention#comment-20150811094822 (ctrl+f for the comment id to jump to it..)

According to the [Ruby parser](https://github.com/G5/microformats2/blob/master/README.md), "Not Implemented: nested microformat without associated property", but adding a property like `u-comment` to the `h-entry` of the threaded replies didn't help either.

**Comment by csarven** [comment]
Just to skip some confusion for debugging this, the fragments on my interactions are now using `i-` (changed from `comment-`) as prefix.

I've sent new mentions to (update/delete?) the old ones, and http://webmention.io/api/mentions?target=http://rhiaro.co.uk/2015/08/threaded-replies appears to be stuck.

Last test (in order to delete the old URIs) was like this from the command-line:

$ source_url="http://csarven.ca/webmention#comment-20150811122226"; target_url="http://rhiaro.co.uk/2015/08/threaded-replies"; curl -i -d "source=$source_url&target=$target_url" `curl -i -s $target_url | grep 'rel="webmention"' | sed 's/rel="webmention"//' | grep -o -E 'https?://[^ ">]+' | sort | uniq`
HTTP/1.1 202 Accepted
Content-Type: application/json;charset=UTF-8
Content-Length: 49
Connection: keep-alive
Status: 202 Accepted
cache-control: no-store
access-control-allow-origin: *
x-content-type-options: nosniff
Date: Sun, 16 Aug 2015 12:14:05 GMT
X-Powered-By: Phusion Passenger 5.0.6
Server: nginx/1.6.3 + Phusion Passenger 5.0.6

IIRC, I got pretty much the same HTTP response when the two replies (which are stuck now) were originally sent.

**Comment by csarven** [comment]
The first mention didn't have an "associated property" with the `h-entry`, however the second included `h-entry u-interaction`. At the time of this writing, I'm still using `h-entry u-interaction`.

**Comment by aaronpk** [comment]
I switched webmention.io to use the PHP parser with (some other smarts) by having it use https://github.com/aaronpk/XRay as an API instead. However, this won't immediately solve the problem you're seeing yet, until https://github.com/aaronpk/XRay/issues/8 is resolved. (Also it looks like the fragment identifiers have changed to http://csarven.ca/webmention#i-20150811122226 now?)

**Comment by aaronpk** [comment]
I'm closing this since https://github.com/aaronpk/XRay/issues/8 is resolved, and it appears there is no longer microformats markup on csarven.ca
